### ISSUE TITLE
[boringyuri-processor] Investigate how to port existing annotation processors to KSP

### ISSUE THREAD

**Issue by anton-novikau** [anton-novikau/boringYURI#24]
Since Google [released](https://android-developers.googleblog.com/2021/09/accelerated-kotlin-build-times-with.html) a stable version of KSP it makes sense to investigate how to port all the declared annotation processors to KSP and think how the library can work in pure java, hybrid (kotlin+java) and kotlin only environments.

**Comment by bomiyr** [comment]
Any news about KSP support?

**Comment by bomiyr** [comment]
Probably I can help with migration to KSP. I suggest to create new KSP processor and copy current implementation there, because universal solution for both kapt and ksp will take much more time. wdyt?

**Comment by anton-novikau** [comment]
@bomiyr I haven't started researching the KSP migration to be perfectly honest. Ideally I wouldn't drop support of `kapt` as it would mean that we would drop support of Java as well, which might be a too big step to make. From what I understand KSP processes annotations in Kotlin files only, so it would break break support of the mixed code base where kotlin and java coexist in the same project. 

I thought it would make sense to approach to this task in two phases:
1. Make the class generation abstract enough to not depend a lot on `JavaPoet`, then generate kotlin classes for annotations in kotlin files using `KotlinPoet`, but to keep generating java classes for annotations in java. 
2. Add `ksp` processors that will use `KotlinPoet` powered abstraction, while the logic for building the structure of classes can be shared between `ksp` and `apt`. This way there going to be one artefact for Kotlin + Java mixed clients (the ones that use `apt` or `kapt`) and one artefact for kotlin-only clients. 

However I agree that this could be more time consuming and probably it doesn't make much sense. Especially taking into account that probably there are not so many clients who use this library to worry about backward compatibility that much. 

Anyway if you're willing to help with the migration, fire away. Create a pull request and I'll see how does it fit. Maybe it indeed would make sense to have a copy of processors implementation for a while and then think on extracting the commons in the next release.

**Comment by bomiyr** [comment]
@anton-novikau I don't suggest to drop kapt support, but just add KSP support separately from kapt processors logic.
It is not true that KSP can't process java files. It can and work in mixed projects, (but it can't get classes generated from kapt).
Ideally, to have same codebase you need to abstract not only javapoet/kotlinpoet, but also processors classes (TypeMirror, Element etc. in kapt, and KSClassDeclaration, KSName etc. in ksp.)
If creating an abstraction for (kotlin/java)poet seems not too difficult (limited solution, just what we need), generalize processors logic is not so easy.
Anyway, I'll try to think about that after digging up your code.

**Comment by bomiyr** [comment]
@anton-novikau please, review my MR for KSP integration https://github.com/anton-novikau/boringYURI/pull/39
